package GUI;

/**
 * created by Ariel
 *
 * enum for specifying a DB action failure
 */
public enum DBActionFailureEnum {

	DB_CONN_FAILURE,
	SEARCH_FAILURE,
	GET_SONGS_FAILURE,
	MAKE_SALE_FAILURE,
	CHECK_AVAIL_FAILURE,
	PLACE_ORDER_FAILURE,
	INIT_ORDERS_FAILURE,
	ORDERS_ACTION_FAILURE,
	INIT_REQUESTS_FAILURE,
	REQUESTS_ACTION_FAILURE,
	UPDATE_DB_FAILURE,
	INIT_EMP_FAILURE,
	INSERT_SAVE_EMP_FAILURE,
	REM_EMP_FAILURE;
	
}
